export type Marker = {
  id: number;
  cx: number;
  cy: number;
  author: string;
  from?: string;
  description: string;
  url: string;
  type: "artist" | "writer";
  imageUrl: string;
  mapId: number;
};

export const goldegAge: Marker[] = [
  {
    id: 1,
    cx: 700,
    cy: 200,
    type: "artist",
    imageUrl: "/images/1.webp",
    author: "Суриков Василий Иванович (1848-1916)",
    description: "Сибирская красавица(1891)- написана в Красноярске",
    url: "https://my.tretyakov.ru/app/masterpiece/8464",
    mapId: 59,
  },
  {
    id: 2,
    cx: 140,
    cy: 220,
    type: "artist",
    imageUrl: "/images/2.webp",
    author: "Борисов Александр Алексеевич (1866-1934)",
    description: "На Мурмане. Близ гавани(1896) - была написана в Мурмане (ныне Кольский полуостров)",
    url: "https://my.tretyakov.ru/app/masterpiece/22072",
    mapId: 50,
  },
  {
    id: 3,
    cx: 170,
    cy: 660,
    type: "artist",
    imageUrl: "/images/5.webp",
    author: "Айвазовский Иван Константинович (1817-1900)",
    description: "Ялта(1866) - написана в Феодосии (Крым)",
    url: "https://my.tretyakov.ru/app/masterpiece/10946",
    mapId: 35,
  },
  {
    id: 4,
    cx: 90,
    cy: 370,
    type: "artist",
    imageUrl: "/images/3.webp",
    author: "Шишкин Иван Иванович (1832-1898)",
    description: "Дубки под Сестрорецком(1857) - написана в Сестрорецк(Санкт-Петербург)",
    url: "https://my.tretyakov.ru/app/masterpiece/20755",
    mapId: 23,
  },
  {
    id: 5,
    cx: 170,
    cy: 440,
    type: "artist",
    imageUrl: "/images/4.webp",
    author: "Репин Илья Ефимович (1844-1930)",
    description:
      "Запорожцы пишут письмо турецкому султану (1880-1890) - первые наброски в селе Абрамцево (Московская обл.)",
    url: "https://my.tretyakov.ru/app/masterpiece/8435",
    mapId: 51,
  },
  {
    id: 6,
    cx: 220,
    cy: 450,
    type: "writer",
    imageUrl: "/images/6.webp",
    author: "Александр Сергеевич Пушкин (1799–1837)",
    description: "Самые известные произведения: «Евгений Онегин», «Капитанская дочка»",
    from: "Родился в Москве. Жил: Москва, Санкт-Петербург, Царское Село, Михайловское, Одесса",
    url: "https://www.culture.ru/persons/8195/aleksandr-pushkin",
    mapId: 52,
  },
  {
    id: 7,
    cx: 210,
    cy: 440,
    type: "writer",
    imageUrl: "/images/7.webp",
    author: "Михаил Юрьевич Лермонтов (1814–1841)",
    description: "Самые известные произведения: «Герой нашего времени», «Мцыри». ",
    from: "Родился в Москве. Жил: Москва, Санкт-Петербург, Кавказ",
    url: "https://www.culture.ru/persons/8188/mikhail-lermontov",
    mapId: 52,
  },
  {
    id: 8,
    cx: 130,
    cy: 370,
    type: "writer",
    imageUrl: "/images/8.webp",
    author: "Николай Васильевич Гоголь (1809–1852)",
    description: "Самые известные произведения: «Мёртвые души», «Ревизор».",
    from: "Родился в Великие Сорочинцы. Жил: Санкт-Петербург, Москва, Рим (много путешествовал)",
    url: "https://www.culture.ru/persons/8127/nikolai-gogol",
    mapId: 23,
  },
  {
    id: 9,
    cx: 200,
    cy: 500,
    type: "writer",
    imageUrl: "/images/9.webp",
    author: "Иван Сергеевич Тургенев (1818–1883)",
    description: "Самые известные произведения: «Отцы и дети», «Муму».",
    from: "Родился в Орёл, Российская империя. Жил: Орёл, Москва, Санкт-Петербург, Германия, Франция (Много лет жил за границей.)",
    url: "https://www.culture.ru/persons/8217/ivan-turgenev",
    mapId: 43,
  },
  {
    id: 10,
    cx: 220,
    cy: 475,
    type: "writer",
    imageUrl: "/images/10.webp",
    author: "Лев Николаевич Толстой (1828–1910)",
    description: "Самые известные произведения: «Война и мир», «Анна Каренина».",
    from: "Родился в Ясная Поляна, Тульская губерния. Жил: Ясная Поляна, Москва, Санкт-Петербург, Кавказ, Крым (служба и путешествия)",
    url: "https://www.culture.ru/persons/8211/lev-tolstoi",
    mapId: 13,
  },
];
export const silverAge: Marker[] = [];
export const contemporary: Marker[] = [
  {
    id: 1,
    cx: 1470,
    cy: 400,
    author: "Ворошилов Владимир Иванович (1943)",
    description: "Камчатская осень (2007) - камчатский край",
    url: "https://old.pkgo.ru/VVoroshilov.html",
    type: "artist",
    mapId: 68,
    imageUrl: "/images/11.webp",
  },
  {
    id: 2,
    cx: 90,
    cy: 415,
    author: "Лысюк Виктор Владимирович (1954)",
    description: "«Псковский Кремль» (2007) - Псковская область",
    url: "https://pskoviana.ru/istoriya/persony/khudozhniki/3609-lysyuk-viktor-vladimirovich",
    type: "artist",
    mapId: 39,
    imageUrl: "/images/12.webp",
  },
  {
    id: 3,
    cx: 115,
    cy: 280,
    author: "Чекмасов Валентин Сергеевич (1940)",
    description: "Лоухские болота (закат). (1992)- написана в Республики Карелия.",
    url: "https://art-karelia.ru/artist/view/19",
    type: "artist",
    mapId: 31,
    imageUrl: "/images/13.webp",
  },
  {
    id: 4,
    cx: 690,
    cy: 510,
    author: "Анатолий Афанасьевич Дрилёв (1938)",
    description: "Площадь Спартака. Оттепель. (1990) - написана в городе Барнауле (Алтайский край)",
    url: "https://rusmuseumvrm.ru/data/city_walks/barnaul/index.php",
    type: "artist",
    mapId: 86,
    imageUrl: "/images/14.webp",
  },
  {
    id: 5,
    cx: 1180,
    cy: 480,
    author: "Дроздов Сергей Анатольевич (1976)",
    description:
      "Покров Пресвятой Богородицы в храме г. Благовещенска(2007)- написана в г.Благовещенск (Амурская область)",
    url: "https://apootcx.ru/chleny-aroo-tsx/%d0%b4%d1%80%d0%be%d0%b7%d0%b4%d0%be%d0%b2-%d1%81%d0%b5%d1%80%d0%b3%d0%b5%d0%b9-%d0%b0%d0%bd%d0%b0%d1%82%d0%be%d0%bb%d1%8c%d0%b5%d0%b2%d0%b8%d1%87/",
    type: "artist",
    mapId: 84,
    imageUrl: "/images/15.webp",
  },
  {
    id: 6,
    cx: 220,
    cy: 440,
    author: "Виктор Олегович Пелевин (1962)",
    description: "Самое известное произведение - «Generation П» (1999)",
    from: "Москва, СССР",
    url: "https://www.livelib.ru/author/2355-viktor-pelevin",
    type: "writer",
    mapId: 52,
    imageUrl: "/images/16.webp",
  },
  {
    id: 7,
    cx: 930,
    cy: 420,
    author: "Андрей Валерьевич Геласимов (1966)",
    description: "Самое известное произведение - «Жажда» (2002)",
    from: "Иркутск, РСФСР, СССР",
    url: "https://www.livelib.ru/author/124506-andrej-gelasimov",
    type: "writer",
    mapId: 74,
    imageUrl: "/images/17.webp",
  },
  {
    id: 8,
    cx: 260,
    cy: 460,
    author: "Евгений Николаевич Прилепин (1975)",
    description: "Самое известное произведение - «Обитель» (2014)",
    from: "с. Ильинка, Скопинский район, Рязанская область, РСФСР",
    url: "https://www.livelib.ru/author/150374-zahar-prilepin",
    type: "writer",
    mapId: 24,
    imageUrl: "/images/18.webp",
  },
  {
    id: 9,
    cx: 750,
    cy: 450,
    author: "Евгений Валерьевич Гришковец (1967)",
    description: "Самое известное произведение - «Рубашка» (2004)",
    from: "Кемерово, РСФСР, СССР",
    url: "https://www.livelib.ru/author/29727-evgenij-grishkovets",
    type: "writer",
    mapId: 66,
    imageUrl: "/images/19.webp",
  },
  {
    id: 10,
    cx: 290,
    cy: 410,
    author: "Алексей Викторович Иванов (1969)",
    description: "Самое известное произведение - «Сердце Пармы» (2003)",
    from: "Горький, СССР (Нижний Новгород)",
    url: "https://www.livelib.ru/author/28724-aleksej-ivanov",
    type: "writer",
    mapId: 48,
    imageUrl: "/images/20.webp",
  },
];
